[project]
name = "mltp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.43.75",
    "dvc[s3]>=3.67.1",
    "huggingface-hub>=1.32.0",
    "ipykernel>=7.3.0",
    "mlflow>=3.16.1",
    "psycopg2-binary>=2.9.13",
    "python-dotenv>=1.2.3",
]
